// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VehicleDiagnosticAPI.Data;

#nullable disable

namespace VehicleDiagnosticAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260523122658_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VehicleDiagnosticAPI.Models.VehicleStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CoolantLevel")
                        .HasColumnType("int");

                    b.Property<bool>("EmergencyMode")
                        .HasColumnType("bit");

                    b.Property<int>("EngineTemperature")
                        .HasColumnType("int");

                    b.Property<bool>("FanActive")
                        .HasColumnType("bit");

                    b.Property<int>("OilPressure")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VehicleStatuses");
                });
#pragma warning restore 612, 618
        }
    }
}
